// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CircuitDbContext))]
    [Migration("20251205215703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Circuit", b =>
                {
                    b.Property<int>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CircuitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuit", (string)null);
                });

            modelBuilder.Entity("Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComponentId"));

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ComponentId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Component", (string)null);

                    b.HasDiscriminator<string>("ComponentType").HasValue("Component");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wire", b =>
                {
                    b.Property<int>("WireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WireId"));

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int>("EndId")
                        .HasColumnType("int");

                    b.Property<int>("StartId")
                        .HasColumnType("int");

                    b.HasKey("WireId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Wire", (string)null);
                });

            modelBuilder.Entity("Battery", b =>
                {
                    b.HasBaseType("Component");

                    b.Property<double>("Emf")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Battery");
                });

            modelBuilder.Entity("Lamp", b =>
                {
                    b.HasBaseType("Component");

                    b.Property<double>("Power")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Lamp");
                });

            modelBuilder.Entity("Resistor", b =>
                {
                    b.HasBaseType("Component");

                    b.Property<double>("Resistance")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Resistor");
                });

            modelBuilder.Entity("Component", b =>
                {
                    b.HasOne("Circuit", null)
                        .WithMany("Components")
                        .HasForeignKey("CircuitId");
                });

            modelBuilder.Entity("Wire", b =>
                {
                    b.HasOne("Circuit", null)
                        .WithMany("Wires")
                        .HasForeignKey("CircuitId");
                });

            modelBuilder.Entity("Circuit", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Wires");
                });
#pragma warning restore 612, 618
        }
    }
}
