// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CircuitDbContext))]
    partial class CircuitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.models.Circuit", b =>
                {
                    b.Property<int>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CircuitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuit", (string)null);
                });

            modelBuilder.Entity("backend.models.Component", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ComponentId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Component", (string)null);

                    b.HasDiscriminator<string>("ComponentType").HasValue("Component");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.models.Wire", b =>
                {
                    b.Property<Guid>("WireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<Guid>("EndId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StartId")
                        .HasColumnType("char(36)");

                    b.HasKey("WireId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Wire", (string)null);
                });

            modelBuilder.Entity("backend.models.Battery", b =>
                {
                    b.HasBaseType("backend.models.Component");

                    b.Property<double>("Emf")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Battery");
                });

            modelBuilder.Entity("backend.models.Lamp", b =>
                {
                    b.HasBaseType("backend.models.Component");

                    b.Property<double>("Power")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Lamp");
                });

            modelBuilder.Entity("backend.models.Resistor", b =>
                {
                    b.HasBaseType("backend.models.Component");

                    b.Property<double>("Resistance")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Resistor");
                });

            modelBuilder.Entity("backend.models.Component", b =>
                {
                    b.HasOne("backend.models.Circuit", "Circuit")
                        .WithMany("Components")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("backend.models.Wire", b =>
                {
                    b.HasOne("backend.models.Circuit", "Circuit")
                        .WithMany("Wires")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("backend.models.Circuit", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Wires");
                });
#pragma warning restore 612, 618
        }
    }
}
